version: "2"
services:
  db:
    image: postgres:10.6
    environment:
      POSTGRES_PASSWORD: messagepassword
      POSTGRES_USER: messageuser
      POSTGRES_DB: messagedb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build:
        context: ./
        dockerfile: ./conf/app/Dockerfile
    depends_on:
      - db 
    ports:
      - '4443:4443'

  proxy:
    build:
      context: ./
      dockerfile: ./conf/nginx/Dockerfile
    depends_on:
      - web 
    ports:
        - 80:80
